### ISSUE TITLE
Preliminary goals

### ISSUE THREAD

**Issue by critiqjo** [critiqjo/lldb.nvim#1]
- [x] Gracefully exit debug mode
- [x] Configurable split layout
- [x] Use a configuration file: (#7 *yet to merge* )
  - [x] ~~The location of the target executable to debug~~
  - [x] ~~or Options to connect to a remote debug server~~
  - [x] ~~or Attach to a process id~~
  - If a new process is to be launched, option to specify:
    - [x] ~~Arguments to pass~~
    - [x] ~~Commands to execute prior to launching~~ (e.g. `make`)
  - [x] Option to save debug session state in it, containing:
    - [x] breakpoints set
    - [x] ...and much more!!
- [x] Input/output without IO redirection (#10 *yet to merge* )

Note: Striked-out points are irrelevant due to the generic design of configuration file.

Inspired from [suggestions](https://github.com/neovim/neovim/pull/2385#issuecomment-91193302) by @tarruda

**Comment by tarruda** [comment]
looking forward to this :smile:
