### ISSUE TITLE
Feature: More configurable highlighting groups

### ISSUE THREAD

**Issue by kennykaye** [critiqjo/lldb.nvim#12]
Currently selected and unselected pc lines  overloads the same highlighting group for the both line and the sign text. I propose these be separated into two different groups as follows:

```viml
sign define llsign_pcsel text=-> linehl=LLSelectedPCLine texthl=LLSelectedPCSign
```

Additionally, I propose the addition of a highlighting group for breakpoint signs:

```viml
sign define llsign_bpres text=B> texthl=LLBreakpointSign
```

If you see the value, I will gladly implement this.

**Comment by critiqjo** [comment]
Good idea! This could come in handy, especially for breakpoint signs... :+1:
