### ISSUE TITLE
importing lldb on Mac OSX dumps fatal error.

### ISSUE THREAD

**Issue by d0u9** [critiqjo/lldb.nvim#16]
Due to the new `SIP` mechanism of El capitan, I installed another python via homebrew. However, when I import the Xcode's lldb library, fatal error is reported.

**Comment by critiqjo** [comment]
I have very *very* little experience with a Mac (and zero with the latest version). So bear with me...

Are you able to run `lldb` as a standalone application?
Are you able to use `lldb` from XCode?
Did you run `xcode-select --install` after the upgrade??
Have you read [this article](https://ohthehugemanatee.org/blog/2015/10/01/how-i-got-el-capitain-working-with-my-developer-tools/)?

If none of that works, please provide more details about the error, and also post the output of
```
>>> import lldb
```
from python2 console.

**Comment by d0u9** [comment]
I tied separately two version python, one is shipped with Xcode, one is installed via homebrew. The pre-installed python works fine, however, the homebrew installed python dumps error.

So, I wonder that whether the `lldb.nvim` provides an option to select which python to be used.

**Comment by critiqjo** [comment]
`lldb.nvim` does not provide any such option, because it doesn't have any control over it.
Neovim has a global option which can be pointed to the pre-installed python, like so:
```vim
let g:python_host_prog = '/path/to/python'
```
Be sure that you can `import neovim` from the pre-installed python, after having python-client installed.
