### ISSUE TITLE
:LLsession new crash while :terminal buffer opened

### ISSUE THREAD

**Issue by frondeus** [critiqjo/lldb.nvim#20]
1. Open some file
```
:e foo.cpp
```
2. Open :terminal
```
:vsp
:terminal
```
3.
```
:Lsession new
```

As a result from :messages
```
E315: ml_get: invalid lnum: 9                                                                                                                                 
E315: ml_get: invalid lnum: 9                                                                                                                                 
E315: ml_get: invalid lnum: 9                                                                                                                                 
Error detected while processing function <SNR>43_Highlight_Matching_Pair:                                                                                     
line   73:                                                                                                                                                    
E315: ml_get: invalid lnum: 42                                                                                                                                
Error detected while processing function <SNR>43_Highlight_Matching_Pair:                                                                                     
line   73:                                                                                                                                                    
E315: ml_get: invalid lnum: 42                                                                                                                                
Error detected while processing function <SNR>43_Highlight_Matching_Pair:                                                                                     
line   92:                                                                                                                                                    
E315: ml_get: invalid lnum: 40                                                                                                                                
Error detected while processing function <SNR>43_Highlight_Matching_Pair:                                                                                     
line   92:                                                                                                                                                    
E315: ml_get: invalid lnum: 40                                                                                                                                
Error detected while processing function <SNR>43_Highlight_Matching_Pair:                                                                                     
line   92:                                                                                                                                                    
E315: ml_get: invalid lnum: 40                                                                                                                                
Error detected while processing function <SNR>43_Highlight_Matching_Pair:                                                                                     
line   92:                                                                                                                                                    
E315: ml_get: invalid lnum: 40                                                                                                                                
Error detected while processing function <SNR>43_Highlight_Matching_Pair:                                                                                     
line   92:                                                                                                                                                    
E315: ml_get: invalid lnum: 40                                                                                                                                
Error detected while processing function <SNR>43_Highlight_Matching_Pair:                                                                                     
line   92:                                                                                                                                                    
E315: ml_get: invalid lnum: 40                                                                                                                                
Error detected while processing function <SNR>43_Highlight_Matching_Pair:                                                                                     
line   92:                                                                                                                                                    
E315: ml_get: invalid lnum: 40                                                                                                                                
Error detected while processing function <SNR>43_Highlight_Matching_Pair:                                                                                     
line   92:                                                                                                                                                    
E315: ml_get: invalid lnum: 40                                                                                                                                
Error detected while processing function <SNR>43_Highlight_Matching_Pair:                                                                                     
line   92:                                                                                                                                                    
E315: ml_get: invalid lnum: 40                                                                                                                                
Error detected while processing function <SNR>43_Highlight_Matching_Pair:                                                                                     
line   92:                                                                                                                                                    
E315: ml_get: invalid lnum: 40                                                                                                                                
Error detected while processing function <SNR>43_Highlight_Matching_Pair:                                                                                     
line   92:                                                                                                                                                    
E315: ml_get: invalid lnum: 40                                                                                                                                
Error detected while processing function <SNR>43_Highlight_Matching_Pair:                                                                                     
line   92:                                                                                                                                                    
E315: ml_get: invalid lnum: 40            
New session created!
```

Without terminal works fine.

**Comment by critiqjo** [comment]
I don't know how this is related... `s:Highlight_Matching_Pair` is from [here](https://github.com/neovim/neovim/blob/536c0ba27e79929eb30850d8e11f2ed026930ab3/runtime/plugin/matchparen.vim#L39), outside of lldb.nvim. Besides that, I'm not able to reproduce the error by repeating those steps.

**Comment by critiqjo** [comment]
Also, since you got the `New session created!` message, and if you were also prompted for session file location and target location, then the `LLsession new` command probably worked fine. Try `:LLsession show` and ensure that your target's location is properly captured in it.

**Comment by frondeus** [comment]
It's probably neovim itself... I tried to reduce my vimrc to minimum:
These two errors happen even without `:terminal`
```
E315: ml_get: invalid lnum: 2
E315: ml_get: invalid lnum: 2
New session created!
```
Steps:
1. vim game.cpp
2. `:vsp game.hpp`
3. `:LLsession new`
4. Default session file
5. Set target

It happens if I set `set foldmethod=syntax` and use `:LLsession new`.
Then my syntax processing in current file disappears...

`lldb.nvim` is only plugin I use (As i said, tried to reduce vimrc).

However `:LLsession show` works and shows me this:
```
{
    "variables": {
        "target": "bin/sdltest"
    },
    "modes": {
        "code": {},
        "debug": {
            "setup": [
                "target create {target}",
                [ "bp", "set" ]
            ],
            "teardown": [
                [ "bp", "save" ],
                "target delete"
            ]
        }
    },
    "breakpoints": {
        "@ll": [
            "breakpoint set -n main"
        ]
    }
}
```

I'll try to reproduce more...

**Comment by frondeus** [comment]
I apologize for the confusion, but I have more info.
First of all it's probably not connected with `:terminal`

I use 'vim-plug'.

I tested some cases with clean init.vim and with full init.vim. 

There are three lines in my init.vim you need to know:
```
Plug 'mhinz/vim-startify'
set hidden
set foldmethod=syntax
```

I use it to load sessions.

But there are cases (like the previous one) which are not connected with plugins at all. There are errors event with clean init.vim

So let's start:

* The previous post - `E315: ml_get: invalid lnum: 2` when `set foldmethod=syntax`
* When I change steps a litlle:

1. vim game.cpp
2. `:vsp game.hpp`
3. `:wincmd l` - to change focus from game.hpp to game.cpp
4. `:LLsession new`
5. Default session file
6. Set target

**There is no error at all.**
No matter if `foldmethod` is set.

* When I load session from 1'st post - let's call it *corrupted one*.
Session has several files, two :terminal and .config/nvim/init.vim opened.
When I simply use `:LLsession new` there are errors described in 1'st post.

* When I load *corrupted session* and close `:bd!` both terminals and init.vim
And then I use `:LLsession new` **there is no error at all**

* When I load *corrupted session* and I have commented in init.vim **and commented** `set hidden`
There is `E315: ml_get: invalid lnum: 2`

* When I load *corrupted session* and I use `:wincmd l` to change focus... **there is no error at all**

* When I load another session - let's call it *uncorrupted one*
Session has game.cpp, game.hpp and :terminal. Terminal is not necessary. I can have exacly same setup like in previous post.
When I simply use `:LLsession new` - **there is no error at all**
No mather what's in init.vim

I checked other plugins and lines in init.vm - there is no difference.

**Comment by critiqjo** [comment]
I tried many combinations, but still couldn't reproduce the error. (Though, if I set `nohidden`, open a terminal, and do `:LLsession new` with focus on the terminal, the terminal vanishes, leaving `[lldb]threads` in its place, but there's no error.)

Can you paste the *corrupted session file* [here](http://pastie.org/) and share a link, and also with your `init.vim` used at the time?

Which version of Neovim are you using? (I use v0.1.1)

**Comment by frondeus** [comment]
NVIM 0.1.1-1 (compiled Dec  5 2015 22:03:57)
with python-neovim 0.1.0-1 and python2-neovim 0.1.0-1 from Arch Linux community repo.

Couldn't you reproduce it even with clean `init.vim` only with `foldmethod=syntax`?
https://gist.github.com/frondeus/aab02b0adb29f6a8c52e

Here's *corrupted* https://gist.github.com/frondeus/67e0192c09072e586454

**Comment by critiqjo** [comment]
I'm still not able to reproduce that error!!

[screencast](https://cloud.githubusercontent.com/assets/1436441/12217540/b171385a-b729-11e5-835b-cb3c95f2a7fd.gif)! (The error at the end is due to the terminal window getting closed.)

I used the minimal `init.vim` you provided, and the session file is slightly modified to make paths valid. I too use `neovim` and `python2-neovim` packages from community repo.

Strange! :disappointed:

**Comment by frondeus** [comment]
Thats... Unexpected. What's happens if you open files manually (just two via `vim game.cpp` and `:vsp game.hpp`) ?

I have almost clean system. I installed arch two-three days ago...

**Comment by critiqjo** [comment]
>What's happens if you open files manually

No errors! (I was almost sure having the session file would do the trick!)

`:h E315` says it's an internal vim error. So may be it's related to something else entirely -- [versions](http://pastie.org/10680073) of dependent packages, or even your locale (`LANG=en_US.UTF-8`)! Can't think of anything else that might be different right now...
