### ISSUE TITLE
Breakpoints being placed one line below expected and no LL print

### ISSUE THREAD

**Issue by JoshMarler** [critiqjo/lldb.nvim#25]
I have a weird issue where whenever I use the LLBreakSwitch command/mapping the breakpoint is placed on the line below the current cursor location. Well the breakpoint pointer / B-> character is in the wrong place but the actual lldb output shows the correct line number!?

I'm also finding that I am unable to use LL print and just receive an lldb error: use of undeclared identifier.

Any ideas ? 
Other than these issues the plugin looks really promising and I'm keen to get things up and running.

**Comment by critiqjo** [comment]
> I have a weird issue where whenever I use the LLBreakSwitch command/mapping the breakpoint is placed on the line below the current cursor location.

That is normal. It is because the debugger is not able to precisely locate the line you are trying to set a breakpoint on. Try `LL b <file>:<line>` and you'll observe the same thing. This is usually due to optimizations done during compilation.

> I'm also finding that I am unable to use LL print and just receive an lldb error: use of undeclared identifier.

Which language are you debugging? Make sure you are emitting debug info during compilation.

**Comment by JoshMarler** [comment]
Hey thanks for the response so quickly. 

I'm trying to debug a C++ audio plugin. 

The plugin has been built with debug symbols and is running inside a host which has also been built with debug symbols. 

I'm attaching to the host and am able to hit breakpoints in my plugin code whilst in nvim but just cannot seem to print anuy variables. Just keep running into undeclared identifier errors from lldb

**Comment by JoshMarler** [comment]
FYI I am able to print vars in the exact same build/process when running lldb directly in the terminal

**Comment by critiqjo** [comment]
You are probably trying to print from the wrong frame. Did you do `LL frame select <number>` before trying to print? The highlighted line is the nearest "highlight-able" line in a frame with number >= that of the current frame.

> FYI I am able to print vars in the exact same build/process when running lldb directly in the terminal

May be the frame is automatically selected there? I'm not sure!

Just to be clear, when you do `LL print x`, the plugin simply passes `print x` to lldb's command interpreter -- nothing special! So I doubt whether it is possible to _do_ anything about it from my side...

**Comment by JoshMarler** [comment]
Sorry! 

What an idiot. 

I was on the wrong thread. 

Thanks for the help. That pointed me in the right direction.

**Comment by critiqjo** [comment]
Glad to be of help.

On another note, I think automatically selecting the frame that is highlight-able during a break point hit might improve user experience... But I probably won't go about doing this anytime soon... I haven't been using any debuggers for so long, and have been too lazy to maintain/update this plugin. :)

Well, that's that!

**Comment by revolter** [comment]
> Also appears to have corrected the breakpoint placement issue. My bad!

@JoshMarler, How?
