### ISSUE TITLE
Separate stdio buffer

### ISSUE THREAD

**Issue by Streetwalrus** [critiqjo/lldb.nvim#29]
This would be extremely useful, instead of keeping it all in the log buffer, allow attaching the debugged process to a proper terminal buffer.

**Comment by critiqjo** [comment]
1. Separating out stdio, stderr from log buffer is definitely do-able (and kinda easy). But then there will be a lot of windows to manage. People will have too different opinions about their arrangement that they'll have to do a considerable amount of work "customizing" before they get comfortable...
2. Attaching the debug process to a terminal (inside Neovim or outside) was kinda hard and quirky last time I checked. (May be there was an easy way that I did not know of.) If it is a long running process, I would suggest [attaching to the process](https://github.com/critiqjo/lldb.nvim#how-do-i-attach-to-a-running-process), instead.
3. I'm right now in maintainer mode limited to bug fixing and PR reviewing/merging.
