### ISSUE TITLE
Please state a license

### ISSUE THREAD

**Issue by phmarek** [critiqjo/lldb.nvim#30]
so that eg. Debian can decide whether they can package your plugin.

Thank you!

**Comment by critiqjo** [comment]
It is stated here: https://github.com/critiqjo/lldb.nvim/blob/master/doc/lldb.txt#L286

Should I just include it in the README.md? Or should I consider changing it to MIT? Not sure whether they are compatible. Even now, (probably) nearly 25% of the code is from the original plugin (that was packaged with lldb).

**Comment by phmarek** [comment]
A separate LICENSE file would be the best way, I guess.

**Comment by critiqjo** [comment]
> A separate LICENSE file would be the best way, I guess.

Okay, I'll just copy Neovim's [LICENSE file](https://github.com/neovim/neovim/blob/master/LICENSE) with appropriate changes and change it to Apache and Vim (kinda dual) license... when I find time!

**Comment by phmarek** [comment]
Thank you very much!
