### ISSUE TITLE
Loading coredumps

### ISSUE THREAD

**Issue by nfnty** [critiqjo/lldb.nvim#38]
Is it possible to load coredumps? Can't seem to find a way to do so. From what I can see neither `lldb-server` or `gdbserver` supports it.

**Comment by critiqjo** [comment]
Something like `target create --core <corefile> <executable>` did not work? I haven't tried it in a remote setup, though. See `help target create` for more options.

**Comment by nfnty** [comment]
Ahh, lovely. Thanks. Only have to find a solution to #37 now.
