### ISSUE TITLE
Way of detecting through vimscript what mode nvim is in

### ISSUE THREAD

**Issue by jonathansty** [critiqjo/lldb.nvim#45]
Is there currently a way to detect what mode (debug or code)  nvim is in?

I would like to have different keybindings depending on the mode.

**Comment by critiqjo** [comment]
There is a callback that can be customized when switching mode. Change the environment variable `g:lldb#session#mode_setup` to the name of the function you want to invoke. By default, it is `'lldb#layout#setup'`. The function you have must take one argument which will be the name of the mode, and finally do `call lldb#layout#setup(a:mode)` to set up the default layout.
