### ISSUE TITLE
Breakpoint symbols not visible

### ISSUE THREAD

**Issue by revolter** [critiqjo/lldb.nvim#47]
Setting a breakpoint with the `:LL breakpoint set` command doesn't update the gutter line with the default `B>` symbol. I recorded an asciinema [here](https://asciinema.org/a/102065).

**Comment by critiqjo** [comment]
You did not pass debuginfo flag (-g) while compiling.

**Comment by revolter** [comment]
Like this:

```
def FlagsForFile( filename, **kwargs ):
  return {
    'flags': [ '-x', 'c', '-g', '-Wall', '-Wextra', '-Werror' ],
  }
```

?

**Comment by revolter** [comment]
Like this: `:!gcc main.c -o main -g`?
